/**
 * Activity Log Types
 * Centralized constants for all activity log action types
 *
 * These constants are used throughout the application to ensure
 * consistent logging and avoid magic strings.
 */

/**
 * Organization Action Types
 */
export const ORG_ACTIONS = {
  CREATED: 'ORG_CREATED',
  UPDATED: 'ORG_UPDATED',
  SELECTED: 'ORG_SELECTED',
  DELETED: 'ORG_DELETED',
  OWNERSHIP_TRANSFERRED: 'ORG_OWNERSHIP_TRANSFERRED',
} as const;

/**
 * User & Member Action Types
 */
export const USER_ACTIONS = {
  INVITED: 'USER_INVITED',
  INVITE_ACCEPTED: 'USER_INVITE_ACCEPTED',
  ROLE_CHANGED: 'USER_ROLE_CHANGED',
  REMOVED: 'USER_REMOVED',
} as const;

/**
 * Pipeline Action Types
 */
export const PIPELINE_ACTIONS = {
  CREATED: 'PIPELINE_CREATED',
  UPDATED: 'PIPELINE_UPDATED',
  PUBLISHED: 'PIPELINE_PUBLISHED',
  RUN_STARTED: 'PIPELINE_RUN_STARTED',
  RUN_PAUSED: 'PIPELINE_RUN_PAUSED',
  RUN_RESUMED: 'PIPELINE_RUN_RESUMED',
  RUN_STOPPED: 'PIPELINE_RUN_STOPPED',
  RUN_FAILED: 'PIPELINE_RUN_FAILED',
  RUN_SUCCEEDED: 'PIPELINE_RUN_SUCCEEDED',
  CONFIGURATION_CHANGED: 'PIPELINE_CONFIGURATION_CHANGED',
} as const;

/**
 * Migration Action Types
 */
export const MIGRATION_ACTIONS = {
  STARTED: 'MIGRATION_STARTED',
  COMPLETED: 'MIGRATION_COMPLETED',
  FAILED: 'MIGRATION_FAILED',
  INCREMENTAL_SYNC_EXECUTED: 'MIGRATION_INCREMENTAL_SYNC_EXECUTED',
  RECORDS_INSERTED: 'MIGRATION_RECORDS_INSERTED',
  RECORDS_UPDATED: 'MIGRATION_RECORDS_UPDATED',
} as const;

/**
 * Data Source Action Types
 */
export const DATASOURCE_ACTIONS = {
  CREATED: 'DATASOURCE_CREATED',
  UPDATED: 'DATASOURCE_UPDATED',
  DELETED: 'DATASOURCE_DELETED',
  VIEWED: 'DATASOURCE_VIEWED',
  TESTED: 'DATASOURCE_TESTED',
  CONNECTED: 'DATASOURCE_CONNECTED',
  DISCONNECTED: 'DATASOURCE_DISCONNECTED',
  SCHEMA_DISCOVERED: 'DATASOURCE_SCHEMA_DISCOVERED',
  SCHEMA_VALIDATION_FAILED: 'DATASOURCE_SCHEMA_VALIDATION_FAILED',
} as const;

/**
 * Connection Action Types
 */
export const CONNECTION_ACTIONS = {
  CREATED: 'CONNECTION_CREATED',
  UPDATED: 'CONNECTION_UPDATED',
  DELETED: 'CONNECTION_DELETED',
  TESTED: 'CONNECTION_TESTED',
  VIEWED: 'CONNECTION_VIEWED',
  SCHEMA_CACHED: 'CONNECTION_SCHEMA_CACHED',
  CONFIGURED: 'CONNECTION_CONFIGURED',
} as const;

/**
 * Source Schema Action Types
 */
export const SOURCE_SCHEMA_ACTIONS = {
  CREATED: 'SOURCE_SCHEMA_CREATED',
  UPDATED: 'SOURCE_SCHEMA_UPDATED',
  DELETED: 'SOURCE_SCHEMA_DELETED',
  DISCOVERED: 'SOURCE_SCHEMA_DISCOVERED',
  VALIDATED: 'SOURCE_SCHEMA_VALIDATED',
} as const;

/**
 * Destination Schema Action Types
 */
export const DESTINATION_SCHEMA_ACTIONS = {
  CREATED: 'DESTINATION_SCHEMA_CREATED',
  UPDATED: 'DESTINATION_SCHEMA_UPDATED',
  DELETED: 'DESTINATION_SCHEMA_DELETED',
  VALIDATED: 'DESTINATION_SCHEMA_VALIDATED',
  SYNCED: 'DESTINATION_SCHEMA_SYNCED',
} as const;

/**
 * Pipeline Run Action Types
 */
export const PIPELINE_RUN_ACTIONS = {
  STARTED: 'PIPELINE_RUN_STARTED',
  COMPLETED: 'PIPELINE_RUN_COMPLETED',
  FAILED: 'PIPELINE_RUN_FAILED',
  CANCELLED: 'PIPELINE_RUN_CANCELLED',
  VIEWED: 'PIPELINE_RUN_VIEWED',
} as const;

/**
 * Query Action Types
 */
export const QUERY_ACTIONS = {
  EXECUTED: 'QUERY_EXECUTED',
  VIEWED: 'QUERY_LOGS_VIEWED',
} as const;

/**
 * Authentication Action Types
 */
export const AUTH_ACTIONS = {
  LOGIN: 'USER_LOGIN',
  LOGOUT: 'USER_LOGOUT',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
  PASSWORD_RESET: 'PASSWORD_RESET',
} as const;

/**
 * Destination Action Types
 */
export const DESTINATION_ACTIONS = {
  CONNECTED: 'DESTINATION_CONNECTED',
  UPDATED: 'DESTINATION_UPDATED',
  DELETED: 'DESTINATION_DELETED',
  UPSERT_CONSTRAINT_MISSING: 'DESTINATION_UPSERT_CONSTRAINT_MISSING',
} as const;

/**
 * Transformation & Mapping Action Types
 */
export const MAPPING_ACTIONS = {
  FIELD_MAPPING_CREATED: 'FIELD_MAPPING_CREATED',
  FIELD_MAPPING_UPDATED: 'FIELD_MAPPING_UPDATED',
  FIELD_MAPPING_DELETED: 'FIELD_MAPPING_DELETED',
  TRANSFORMATION_VALIDATION_FAILED: 'TRANSFORMATION_VALIDATION_FAILED',
  TRANSFORMATION_VALIDATION_SUCCEEDED: 'TRANSFORMATION_VALIDATION_SUCCEEDED',
} as const;

/**
 * Entity Types
 */
export const ENTITY_TYPES = {
  ORGANIZATION: 'organization',
  PIPELINE: 'pipeline',
  PIPELINE_RUN: 'pipeline_run',
  MIGRATION: 'migration',
  DATASOURCE: 'data_source',
  CONNECTION: 'data_source_connection',
  DESTINATION: 'destination',
  SOURCE_SCHEMA: 'pipeline_source_schema',
  DESTINATION_SCHEMA: 'pipeline_destination_schema',
  USER: 'user',
  MEMBER: 'organization_member',
  MAPPING: 'mapping',
  QUERY: 'query_log',
} as const;

/**
 * All action types combined
 */
export const ACTIVITY_LOG_ACTIONS = {
  ...ORG_ACTIONS,
  ...USER_ACTIONS,
  ...PIPELINE_ACTIONS,
  ...PIPELINE_RUN_ACTIONS,
  ...MIGRATION_ACTIONS,
  ...DATASOURCE_ACTIONS,
  ...CONNECTION_ACTIONS,
  ...SOURCE_SCHEMA_ACTIONS,
  ...DESTINATION_SCHEMA_ACTIONS,
  ...DESTINATION_ACTIONS,
  ...MAPPING_ACTIONS,
  ...QUERY_ACTIONS,
  ...AUTH_ACTIONS,
} as const;

/**
 * Type for action type values
 */
export type ActivityLogActionType =
  | (typeof ORG_ACTIONS)[keyof typeof ORG_ACTIONS]
  | (typeof USER_ACTIONS)[keyof typeof USER_ACTIONS]
  | (typeof PIPELINE_ACTIONS)[keyof typeof PIPELINE_ACTIONS]
  | (typeof PIPELINE_RUN_ACTIONS)[keyof typeof PIPELINE_RUN_ACTIONS]
  | (typeof MIGRATION_ACTIONS)[keyof typeof MIGRATION_ACTIONS]
  | (typeof DATASOURCE_ACTIONS)[keyof typeof DATASOURCE_ACTIONS]
  | (typeof CONNECTION_ACTIONS)[keyof typeof CONNECTION_ACTIONS]
  | (typeof SOURCE_SCHEMA_ACTIONS)[keyof typeof SOURCE_SCHEMA_ACTIONS]
  | (typeof DESTINATION_SCHEMA_ACTIONS)[keyof typeof DESTINATION_SCHEMA_ACTIONS]
  | (typeof DESTINATION_ACTIONS)[keyof typeof DESTINATION_ACTIONS]
  | (typeof MAPPING_ACTIONS)[keyof typeof MAPPING_ACTIONS]
  | (typeof QUERY_ACTIONS)[keyof typeof QUERY_ACTIONS]
  | (typeof AUTH_ACTIONS)[keyof typeof AUTH_ACTIONS];

/**
 * Type for entity type values
 */
export type ActivityLogEntityType = (typeof ENTITY_TYPES)[keyof typeof ENTITY_TYPES];
